# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - eyou_test_controller

  eyou_test_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - motor_joint_13
      - motor_joint_10