# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    eyou_test_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

eyou_test_controller:
  ros__parameters:
    joints:
      - motor_joint_13
      - motor_joint_10
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity